title: Stephen Ajulu
baseURL: /
params:
  color_scheme: dark
  accent_color: violet
  base_font: fraunces
  header:
    type: header
    template: header
    title: Stephen Ajulu
    logo: /images/signature-white-black.png
    logo_alt: Stephen Ajulu
    has_nav: true
    nav_links:
      - type: action
        template: action
        label: Home
        url: /
        style: link
      - type: action
        template: action
        label: Work
        url: /portfolio/
        style: link
      - type: action
        template: action
        label: Journal
        url: /blog/
        style: link
      - type: action
        template: action
        label: About
        url: /about/
        style: link
      - type: action
        template: action
        label: Contact
        url: /contact/
        style: button
  footer:
    type: footer
    template: footer
    content: 2016 - Today | &copy; Stephen Ajulu.&nbsp; All rights reserved.
    has_social: true
    social_links:
      - type: action
        template: action
        label: Follow Stephen Ajulu On Twitter
        url: 'https://twitter.com/stephenajulu'
        style: icon
        icon: twitter
        new_window: true
      - type: action
        template: action
        label: Follow Stephen Ajulu on Instagram
        url: 'https://www.instagram.com/stephenajulu.com'
        style: icon
        icon: instagram
        new_window: true
      - type: action
        template: action
        label: Check Out Stephen Ajulu's Professional Profile on LinkedIn
        url: 'https://www.linkedin.com/in/stephenajulu'
        style: icon
        icon: linkedin
        new_window: true
      - label: Check Out Stephen Ajulu's Projects on GitHub
        style: icon
        icon: github
        new_window: true
        no_follow: false
        type: action
        url: 'https://github.com/stephenajulu/'
      - label: Take a Look at Stephen Ajulu's Videos on YouTube
        url: '#'
        style: icon
        icon: youtube
        new_window: true
        no_follow: false
        type: action
      - label: Hire Me â†’
        url: /contact
        style: link
        icon: dribbble
        new_window: true
        no_follow: false
        type: action
      - label: RSS
        url: /index.xml
        style: link
        icon: dribbble
        new_window: true
        no_follow: false
        type: action
  domain: 'https://stephenajulu13-21bb7.netlify.app'
  favicon: /images/me.png
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
